###from django.core.exceptions import ValidationError
##

class %(class_name)s:
    def __init__(self):
        ...

    def __call__(self):
        return True
