WORKING

python3 -m unittest tests.test_sidecar
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ws is connecting to wss://r2lab.inria.fr:999/socket.io/?EIO=3&transport=websocket&sid=trnYPKVxOKB0STawAABW
2018-03-18 16:40:28,675 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io packet sent] 2["request:nodes", "PLEASE"]
2018-03-18 16:40:28,728 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [engine.io message] b'0'
2018-03-18 16:40:28,728 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io packet received] b'0'
2018-03-18 16:40:28,728 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io connect]
2018-03-18 16:40:28,728 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io connected]
2018-03-18 16:40:28,729 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [engine.io pong] b''
2018-03-18 16:40:28,787 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [engine.io message] b'2["info:nodes", blablabla]
2018-03-18 16:40:28,818 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io disconnect]


BROKEN

python3 -m unittest tests.test_sidecar
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
ws is connecting to wss://r2lab.inria.fr:999/socket.io/?EIO=3&transport=websocket&sid=kN84OV23yTeiRQiaAABX
2018-03-18 16:40:29,748 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io packet sent] 2["request:nodes", "PLEASE"]
2018-03-18 16:40:29,804 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [engine.io message] b'0'
2018-03-18 16:40:29,804 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io packet received] b'0'
2018-03-18 16:40:29,805 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io connect]
2018-03-18 16:40:29,805 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io connected]
2018-03-18 16:40:29,805 - socketIO-client - WARNING - r2lab.inria.fr:999/socket.io [connection error] recv disconnected (Connection is already closed.)
2018-03-18 16:40:30,806 - socketIO-client - WARNING - r2lab.inria.fr:999/socket.io [connection error] recv disconnected (Connection is already closed.)
2018-03-18 16:40:30,806 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io disconnect]
ws is connecting to wss://r2lab.inria.fr:999/socket.io/?EIO=3&transport=websocket&sid=9bpbJIblkD9z8VB6AABY
2018-03-18 16:40:31,146 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [engine.io transport selected] websocket
2018-03-18 16:40:31,147 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [engine.io heartbeat reset]
2018-03-18 16:40:31,147 - socketIO-client - DEBUG - r2lab.inria.fr:999/socket.io [socket.io disconnect]
